- hosts: quobyteservers
  become: yes
  ignore_errors: yes
  tasks:

    - set_fact: 
        package_url: https://packages.quobyte.com/repo/v3 

    - set_fact: 
        rpm_distribution_string: RHEL 
      when: ansible_facts['os_family'] == "RedHat"

    - name: stop Quobyte data consuming services  
      ignore_errors: yes
      service:
        state: stopped
        enabled: false 
        name: "{{ item }}"
      with_items:
        - quobyte-nfs
        - quobyte-s3
        - quobyte-metadata
        - quobyte-data
        - quobyte-api
        - quobyte-registry
        - quobyte-data
        - quobyte-webconsole
        - quobyte-client

    - name: build device list
      shell:
        cmd: mount | grep /var/lib/quobyte | awk '{print $1}'
      register: quobyte_devices 

    - set_fact: 
       devices_to_wipe: "{{ quobyte_devices.stdout_lines }}"

    - name: umount devices
      command: 
        cmd: umount {{ item }}
      with_items:
        - "{{ devices_to_wipe }}"

    - name: wipe devices
      command: 
        cmd: wipefs -a {{ item }}
      with_items:
        - "{{ devices_to_wipe }}"

    - name: update device labels
      command: 
        cmd: partprobe {{ item }}
      with_items:
        - "{{ devices_to_wipe }}"

    - name: remove RPM packages
      yum: 
        update_cache: no 
        state: absent
        name: "{{ packages }}"
      vars:
        packages:
        - quobyte-server
        - quobyte-tools
        - quobyte-client 
        - quobyte-thirdparty-libraries
      when: ansible_facts['os_family'] == "RedHat"

    - name: Remove Quobyte rpm repository to sources list
      yum_repository:
        name: quobyte
        description: Quobyte rpm repo
        baseurl: "{{ package_url }}/rpm/{{ rpm_distribution_string }}_{{ ansible_distribution_major_version }}"
        state: absent
      when: ansible_facts['os_family'] == "RedHat"

    - name: Clear rpm package cache
      command:
        cmd: dnf clean all
      when: ansible_facts['os_family'] == "RedHat"

    - name: solve dependency conflicts for half installe packages
      command:
        cmd: dpkg --configure -a
      when: ansible_facts['os_family'] == "Debian"

    - name: remove Debian packages
      apt:
        name: "{{ packages }}"
        state: absent 
        purge: yes
      vars:
        packages:
        - quobyte-thirdparty-libraries
        - quobyte-server
        - quobyte-tools
        - quobyte-client
      when: ansible_facts['os_family'] == "Debian"

    - name: Remove Quobyte apt repository to sources list
      apt_repository:
        repo: "deb {{ package_url }}/apt {{ ansible_distribution_release }} main"
        state: absent 
      when: ansible_facts['os_family'] == "Debian"

    - name: Remove Quobyte directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/quobyte
        - /etc/quobyte 
        - /quobyte 

    - name: Remove Quobyte apt repository from sources list
      apt_repository:
        repo: "deb {{ package_url }}/apt {{ ansible_distribution_release }} main"
        state: absent 
      when: ansible_facts['os_family'] == "Debian"

