- hosts: dataservices 
  serial: 1
  vars_files:
    - ../vars/ansible-vars
  become: yes
  tasks:
    - name: get Quobyte session 
      shell:
        cmd: qmgmt -u {{ api_service }} user login {{ admin_user }} {{ admin_password }} 

    - name: wait for healthmanager to react
      pause: 
        seconds: 30

    - name: Test if cluster is HEALTHY 
      shell:
        cmd: qmgmt -u {{ api_service }} healthmanager status | grep system_health | awk '{print $2}'
      register: systemhealth_test
      retries: 50
      delay: 5
      until: "'HEALTHY' in systemhealth_test.stdout"

    - debug:
        var: systemhealth_test

    - name: restart very important service 
      service:
        state: restarted
        name: quobyte-data
      when: "'HEALTHY' in systemhealth_test.stdout"

