- hosts: registryservices 
  become: yes
  gather_facts: no
  tasks:
    - name: Start Quobyte registry services 
      service:
        state: started 
        name: quobyte-registry 

- hosts: apiservices 
  become: yes
  gather_facts: no
  tasks:
    - name: Start Quobyte api services 
      service:
        state: started
        name: quobyte-api 

- hosts: webconsoleservices 
  become: yes
  gather_facts: no
  tasks:
    - name: Start Quobyte webconsole services 
      service:
        state: started
        name: quobyte-webconsole 

- hosts: metadataservices 
  become: yes
  gather_facts: no
  tasks:
    - name: Start Quobyte metadata services 
      service:
        state: started
        name: quobyte-metadata

- hosts: dataservices 
  become: yes
  gather_facts: no
  tasks:
    - name: Start Quobyte dataservices 
      service:
        state: started
        name: quobyte-data

- hosts: s3services 
  become: yes
  gather_facts: no
  tasks:
    - name: Start Quobyte dataservices 
      service:
        state: started
        name: quobyte-s3

