- hosts: registryservices[0]
  vars_files:
    - vars/ansible-vars
  become: yes
  tasks:
    - name: Create API json payload
      blockinfile:
        path: /tmp/getconfig
        create: true
        marker: ""
        block: |
          {
          "id": "text",
          "jsonrpc": "2.0",
          "method": "getConfiguration",
          "params": {
            "configuration_type": "SYSTEM_CONFIGURATION",
            "retry": "INFINITELY"
            }
          }
 
    - name: Dump systemconfig to json file
      shell:
        cmd:  curl -s -u {{admin_user}}:{{admin_password}} http://{{api_service}}:7860 -d @/tmp/getconfig > /tmp/systemconfig.json
      
    - name: Load systemconfig from dump file
      include_vars:
        file: /tmp/systemconfig.json
        name: systemconfig_var

    - debug:
        var: systemconfig_var

    - name: append more key/values
      set_fact:
              systemconfig_var: "{{ systemconfig_var.result.system_configuration | default([]) | combine({ 'cluster_config': { 'clustername': 'fidibar'}}) }}"

    - debug:
        var: systemconfig_var

    - name: write var to file
      copy:
        content: "{{ systemconfig_var | to_nice_json }}"
        dest: /tmp/final.json

    - name: Create API json payload
      blockinfile:
        path: /tmp/setconfig
        create: true
        marker: ""
        block: |
          {
            "id": "text",
            "jsonrpc": "2.0",
            "method": "setConfiguration",
            "params": {
               "configuration_type": "SYSTEM_CONFIGURATION",
               "retry": "INFINITELY",
               "system_configuration": {{ systemconfig_var | to_nice_json }}
            }
          }
 

