# ansible-galaxy collection install ansible.posix #(on rocky at least)
- hosts: metadataservices
  vars_files:
    - vars/ansible-vars
  become: yes
  tasks:

    - name: Enable Quobyte metadata service
      service:
        enabled: yes
        state: started
        name: "{{ item }}"
      with_items: 
         - quobyte-metadata

    - name: Create a xfs filesystem on {{ metadatadevices }}
      filesystem:
        fstype: xfs 
        opts: -isize=1024 -L quobyte-dev
        dev: "{{ item }}"
      with_items: "{{ metadatadevices }}"

    - name: Make sure device labels are up to date 
      command:
        cmd: partprobe {{ item }} 
      with_items: "{{ metadatadevices }}"

    - name: Mount temporary MD device mount
      mount:
        path: "/tmp/{{ item }}"
        src: "{{ item }}"
        state: ephemeral
        fstype: xfs
      with_items: "{{ metadatadevices }}"

    - name: Run qmkdev to create metadata device 
      command:
        cmd: /usr/bin/qmkdev -t METADATA /tmp/{{ item }}
        creates: /tmp/{{ item }}/QUOBYTE_DEV_SETUP
      with_items: "{{ metadatadevices }}"

    - name: Unmount temporary MD device mount
      mount:
        path: "/tmp/{{ item }}"
        src: "{{ item }}"
        state: unmounted
      with_items: "{{ metadatadevices }}"



