- hosts: dataservices
  vars_files:
    - vars/ansible-vars
  become: yes
  tasks:
    - name: Enable Quobyte data service
      service:
        enabled: yes
        state: started
        name: "{{ item }}"
      with_items: 
         - quobyte-data

    - name: Wait for Dataservice RPC port to become available 
      wait_for:
        port: 7863

    - name: Wait for Dataservice metrics port to become available 
      wait_for:
        port: 7873

- hosts: registryservices[0]
  become: yes
  vars_files:
    - vars/ansible-vars
  tasks:

    - name: Wait for device inspector to find any unused devices.
      pause: 
        seconds: 45

    - name: Get Quobyte session 
      shell:
        cmd: qmgmt -u {{ api_service }} user login {{ admin_user }} {{ admin_password }} 
    - name: Create a list of unformatted devices
      ignore_errors: yes
      shell:
        cmd: qmgmt -u {{ api_service }} device list-unformatted | awk '{print $1}' | grep -v -e ^Handle -e ^No
      register: empty_devices 
    - debug: 
       var: empty_devices

    - set_fact: 
       unformatted_devices: "{{ empty_devices.stdout_lines }}"
    - debug: 
        var: unformatted_devices

    - name: Create "make device" tasks 
      shell:
        cmd: qmgmt -u {{ api_service }} device make {{ item }} DATA 
      with_items: "{{ unformatted_devices }}"

    - name: Wait for tasks to finish before proceeding 
      shell: 
        cmd: qmgmt -u {{ api_service }} --output json task list RUNNING SCHEDULED QUEUED 
      register: result
      until: result.stdout.find("MAKE_DEVICE") < 1
      retries: 500
      delay: 10



