- hosts: quobyteservers
  vars_files:
    - vars/ansible-vars
  become: yes
  tasks:
    - name: Get installed packages 
      package_facts:
        manager: auto

    - name: Install chrony if no other time sysnc daemon is installed
      apt:
        name: chrony
        state: present 
      when: ansible_facts['os_family'] == "Debian" and 'ntp' not in ansible_facts.packages and 'ntpsec' not in ansible_facts.packages

    - name: Install tuned package on Debian
      apt: 
        name: tuned
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Install tuned package on Redhat
      yum: 
        name: tuned
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install tuned package on Suse Linux 
      zypper: 
        update_cache: yes
        state: present
        name: tuned 
      when: ansible_facts['os_family'] == "Suse"

    - name: Set Quobyte tuned server profile
      command: tuned-adm profile quobyte-server-performance

    - name: Restart tuned
      service:
        name: tuned
        state: restarted
        enabled: yes

- hosts: registryservices 
  gather_facts: false
  become: yes
  serial: 1
  tasks:
    - name: Restart Quobyte registry services 
      service:
        state: restarted
        name: quobyte-registry 
    - name: Wait for Registry RPC port to become available 
      wait_for:
        port: 7861
        delay: 5 
    - name: Wait for Registry metrics port to become available 
      wait_for:
        port: 7871
        delay: 5

- hosts: apiservices 
  become: yes
  gather_facts: false
  vars_files:
    - vars/ansible-vars
  tasks:
    - name: Restart Quobyte api services 
      service:
        state: restarted
        name: quobyte-api 

    - name: Do a API liveness probe 
      uri:
        url: "http://localhost:7860"
        user: "{{admin_user}}"
        password: "{{admin_password}}"
        force_basic_auth: yes
        method: POST
        body_format: json
        body: "{ \"id\": \"12345\", \"jsonrpc\": \"2.0\", \"method\": \"whoAmI\", \"params\": { \"retry\": \"INFINITELY\" } }"
        return_content: yes
      register: _result 
      until: _result.status == 200
      retries: 720 # 720 * 5 seconds = 1hour (60*60/5)
      delay: 5 # Every 5 seconds

- hosts: webconsoleservices 
  become: yes
  gather_facts: false
  tasks:
    - name: Restart Quobyte webconsole services 
      service:
        state: restarted
        name: quobyte-webconsole 

- hosts: metadataservices 
  become: yes
  gather_facts: false
  serial: 1
  tasks:
    - name: Restart Quobyte metadata services 
      service:
        state: restarted
        name: quobyte-metadata 
    - name: Wait for metadata RPC port to become available 
      wait_for:
        port: 7862
        delay: 2
    - name: Wait for metadata metrics port to become available 
      wait_for:
        port: 7872
        delay: 2

- hosts: dataservices 
  become: yes
  gather_facts: false
  tasks:
    - name: Restart Quobyte data services 
      service:
        state: restarted
        name: quobyte-data 
    - name: Wait for data RPC port to become available 
      wait_for:
        port: 7863
        delay: 2
    - name: Wait for data metrics port to become available 
      wait_for:
        port: 7873
        delay: 2


