- hosts: quobyteservers
  vars_files:
    - vars/ansible-vars
  become: yes
  tasks:
    - name: Install tuned package on Debian
      apt: 
        name: tuned
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Install tuned package on Redhat
      yum: 
        name: tuned
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install tuned package on Suse Linux 
      zypper: 
        update_cache: yes
        state: present
        name: tuned 
      when: ansible_facts['os_family'] == "Suse"

    - name: Set Quobyte tuned server profile
      command: tuned-adm profile quobyte-server-performance

    - name: Restart tuned
      service:
        name: tuned
        state: restarted
        enabled: yes

- hosts: registryservices 
  gather_facts: false
  become: yes
  serial: 1
  tasks:
    - name: Restart Quobyte registry services 
      service:
        state: restarted
        name: quobyte-registry 
    - name: Wait for Registry RPC port to become available 
      wait_for:
        port: 7861
        delay: 2
    - name: Wait for Registry metrics port to become available 
      wait_for:
        port: 7871
        delay: 2

- hosts: apiservices 
  become: yes
  gather_facts: false
  tasks:
    - name: Restart Quobyte api services 
      service:
        state: restarted
        name: quobyte-api 

- hosts: webconsoleservices 
  become: yes
  gather_facts: false
  tasks:
    - name: Restart Quobyte webconsole services 
      service:
        state: restarted
        name: quobyte-webconsole 

- hosts: metadataservices 
  become: yes
  gather_facts: false
  serial: 1
  tasks:
    - name: Restart Quobyte metadata services 
      service:
        state: restarted
        name: quobyte-metadata 
    - name: Wait for metadata RPC port to become available 
      wait_for:
        port: 7862
        delay: 2
    - name: Wait for metadata metrics port to become available 
      wait_for:
        port: 7872
        delay: 2

- hosts: dataservices 
  become: yes
  gather_facts: false
  tasks:
    - name: Restart Quobyte data services 
      service:
        state: restarted
        name: quobyte-data 
    - name: Wait for data RPC port to become available 
      wait_for:
        port: 7863
        delay: 2
    - name: Wait for data metrics port to become available 
      wait_for:
        port: 7873
        delay: 2


