- hosts: registryservices[0] 
  vars_files:
    - vars/ansible-vars
  become: yes
  tasks:

    - name: Prepare temporary license file
      template:
        src: templates/license.txt.jinja2
        dest: "/tmp/qlicense.txt"

    - name: Get Quobyte session 
      shell:
        cmd: qmgmt -u {{ api_service }} user login {{ admin_user }} {{admin_password }} 

    - name: Import Quobyte license from file
      shell:
        cmd: qmgmt -u {{ api_service }} license import /tmp/qlicense.txt 

    - name: Remove temporary license file
      file:
        state: absent
        dest: "/tmp/qlicense.txt"


- hosts: registryservices 
  become: yes
  serial: 1
  tasks:
    - name: Restart Quobyte registry services 
      service:
        state: restarted
        name: quobyte-registry 
    - name: Wait for Registry RPC port to become available 
      wait_for:
        port: 7861
        delay: 2
    - name: Wait for Registry metrics port to become available 
      wait_for:
        port: 7871
        delay: 2



- hosts: apiservices 
  become: yes
  serial: 1
  tasks:
    - name: Restart Quobyte api services 
      service:
        state: restarted
        name: quobyte-api 
    - name: Wait for API RPC port to become available 
      wait_for:
        port: 7865 
        delay: 2
    - name: Wait for API metrics port to become available 
      wait_for:
        port: 7875 
        delay: 2


- hosts: webconsoleservices 
  become: yes
  serial: 1
  tasks:
    - name: Restart Quobyte webconsole services 
      service:
        state: restarted
        name: quobyte-webconsole 

- hosts: metadataservices 
  become: yes
  serial: 1
  tasks:
    - name: Restart Quobyte metadata services 
      service:
        state: restarted
        name: quobyte-metadata

