- hosts: registryservices[0]
  become: yes
  vars_files:
    - vars/ansible-vars
  tasks:
  tasks:
    - name: Get Quobyte session 
      shell:
        cmd: qmgmt -u {{ api_service }} user login {{ admin_user }} {{ admin_password }} 

    - name: Create a list of NVMe devices
      shell:
        cmd: qmgmt -u {{ api_service }} device list DATA --list-columns device_id,device_model,detected_disk_type| grep " SOLID_STATE_DISK_NVME" | awk '{print $1}' 
      register: nvme_devices 

    - name: Create a list of SSD devices
      shell:
        cmd: qmgmt -u {{ api_service }} device list DATA --list-columns device_id,device_model,detected_disk_type| grep " SOLID_STATE_DISK " | awk '{print $1}' 
      register: ssd_devices 

    - name: Create a list of HDD devices
      shell:
        cmd: qmgmt -u {{ api_service }} device list DATA --list-columns device_id,device_model,detected_disk_type| grep " HDD " | awk '{print $1}' 
      register: hdd_devices 

    - set_fact: 
       cleaned_nvme_devices: "{{ nvme_devices.stdout_lines }}"

    - set_fact: 
       cleaned_ssd_devices: "{{ ssd_devices.stdout_lines }}"

    - set_fact: 
       cleaned_hdd_devices: "{{ hdd_devices.stdout_lines }}"

    - name: Tag NVME devices
      shell:
        cmd: qmgmt -u {{ api_service }} device update add-tags {{ item }} platinum 
      with_items: "{{ cleaned_nvme_devices }}" 

    - name: Tag SSD devices
      shell:
        cmd: qmgmt -u {{ api_service }} device update add-tags {{ item }} gold 
      with_items: "{{ cleaned_ssd_devices }}" 

    - name: Tag HDD devices
      shell:
        cmd: qmgmt -u {{ api_service }} device update add-tags {{ item }} silver 
      with_items: "{{ cleaned_hdd_devices }}" 
