- hosts: registryservices[0] 
  vars_files:
    - vars/ansible-vars
  become: yes
  tasks:
    - name: get Quobyte session 
      shell:
        cmd: qmgmt -u {{ api_service }} user login {{ admin_user }} {{ admin_password }} 

    - name: export systemconfig 
      shell:
        cmd: qmgmt -u {{ api_service }} systemconfig export /tmp/systemconfig

    - name: add qns section to systemconfig
      blockinfile:
        path: /tmp/systemconfig
        block: |
          qns_config {
            id: "{{ qns_id }}"
            secret: "{{ qns_secret }}"
          }

    - name: import systemconfig 
      shell:
        cmd: qmgmt -u {{ api_service }} systemconfig import /tmp/systemconfig

- hosts: registryservices 
  vars_files:
    - vars/ansible-vars
  become: yes
  tasks:
    - name: restart Quobyte registries 
      service:
        state: restarted
        name: "{{ item }}"
      with_items: 
         - quobyte-registry

- hosts: s3services 
  become: yes
  vars_files:
    - vars/ansible-vars
  tasks:
    - name: get public ip 
      uri:
        url: http://ip.syseleven.de
        return_content: yes
      register: ipaddress
    - set_fact: 
        public_ip: "public_ip = {{ ipaddress.content | trim }}"

    - debug:
       var: public_ip 

    - name: Add qns config 
      lineinfile:
        path: /etc/quobyte/s3.cfg
        state: present
        line: "qns.id = {{ qns_id }}"

    - name: Add public_ip config 
      lineinfile:
        path: /etc/quobyte/s3.cfg
        state: present
        line: "{{ public_ip }}"

    - name: restart Quobyte S3 proxy
      service:
        state: restarted
        name: "{{ item }}"
      with_items: 
         - quobyte-s3
