- hosts: nfsservices 
  vars_files:
    - vars/ansible-vars
  become: yes
  tasks:

    - name: Install Debian packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - quobyte-nfs
      when: ansible_facts['os_family'] == "Debian"
 
    - name: Install RPM packages
      yum: 
        update_cache: yes
        allow_downgrade: yes
        state: present
        name: "{{ packages }}"
      vars:
        packages:
        - quobyte-nfs
      when: ansible_facts['os_family'] == "RedHat"

    - name: Enable Quobyte NFS proxy
      service:
        enabled: yes
        state: started
        name: "{{ item }}"
      with_items: 
         - quobyte-nfs


