- hosts: quobyteservers 
  become: yes
  tasks:
    - name: remove deprecated environment file 
      file:
        path: /etc/default/quobyte
        state: absent 
    - name: remove deprecated systemd file 
      file:
        path: /etc/systemd/system/quobyte-metadata.service.d/10-memory-cgroup-disabled.conf
        state: absent 

    - name: remove deprecated systemd file 
      file:
        path: /etc/systemd/system/quobyte-data.service.d/10-memory-cgroup-disabled.conf 
        state: absent 

- hosts: dataservices,metadataservices
  become: yes
  tasks:
    - name: Configure dataservice memory consumption
      blockinfile:
        path: /etc/systemd/system.control/quobyte-data.service.d/50-MemoryMaxScale.conf
        state: present
        create: true
        block: | 
          [Service]
          ## MemoryMax=40.0%
          MemoryLimit={{ (ansible_memtotal_mb * 0.4 / 1024) |int|abs }}G
          Environment=MAX_MEM_DATA={{ (ansible_memtotal_mb * 0.1 / 1024) |int|abs }}G
          Environment=MAX_BUFFER_DATA={{ (ansible_memtotal_mb * 0.3 / 1024) |int|abs }}G
    - name: Configure metadataservice memory consumption
      blockinfile:
        path: /etc/systemd/system.control/quobyte-metadata.service.d/50-MemoryMaxScale.conf
        state: present
        create: true
        block: | 
          [Service]
          ## MemoryMax=50.0%
          MemoryLimit={{ (ansible_memtotal_mb * 0.5 / 1024) |int|abs }}G
          Environment=MAX_MEM_METADATA={{ (ansible_memtotal_mb * 0.15 / 1024) |int|abs }}G
          Environment=MAX_BUFFER_METADATA={{ (ansible_memtotal_mb * 0.1 / 1024) |int|abs }}G
    - name: Reload systemd config 
      command: systemctl daemon-reload

- hosts: metadataservices 
  become: yes
  tasks:
    - name: Restart Quobyte metadata services 
      service:
        state: restarted
        name: quobyte-metadata 

- hosts: dataservices 
  become: yes
  tasks:
    - name: Restart Quobyte data services 
      service:
        state: restarted
        name: quobyte-data 


